export const OFFER_LIST_REQUEST='OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS='OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAIL='OFFER_LIST_FAIL'
export const OFFER_LIST_RESET='OFFER_LIST_RESET'

export const OFFER_ADD_REQUEST='OFFER_ADD_REQUEST'
export const OFFER_ADD_SUCCESS='OFFER_ADD_SUCCESS'
export const OFFER_ADD_FAIL='OFFER_ADD_FAIL'
export const OFFER_ADD_RESET='OFFER_ADD_RESET'

export const OFFER_DELETE_REQUEST='OFFER_DELETE_REQUEST'
export const OFFER_DELETE_SUCCESS='OFFER_DELETE_SUCCESS'
export const OFFER_DELETE_FAIL='OFFER_DELETE_FAIL'
export const OFFER_DELETE_RESET='OFFER_DELETE_RESET'

export const COOPEN_ADD_REQUEST='COOPEN_ADD_REQUEST'
export const COOPEN_ADD_SUCCESS='COOPEN_ADD_SUCCESS'
export const COOPEN_ADD_FAIL='COOPEN_ADD_FAIL'
export const COOPEN_ADD_RESET='COOPEN_ADD_RESET'

export const COOPENS_LIST_REQUEST='COOPENS_LIST_REQUEST'
export const COOPENS_LIST_SUCCESS='COOPENS_LIST_SUCCESS'
export const COOPENS_LIST_FAIL='COOPENS_LIST_FAIL'
export const COOPENS_LIST_RESET='COOPENS_LIST_RESET'

export const COOPENS_APPLY_REQUEST='COOPENS_APPLY_REQUEST'
export const COOPENS_APPLY_SUCCESS='COOPENS_APPLY_SUCCESS'
export const COOPENS_APPLY_FAIL='COOPENS_APPLY_FAIL'
export const COOPENS_APPLY_RESET='COOPENS_APPLY_RESET'

export const COOPENS_DELETE_REQUEST='COOPENS_DELETE_REQUEST'
export const COOPENS_DELETE_SUCCESS='COOPENS_DELETE_SUCCESS'
export const COOPENS_DELETE_FAIL='COOPENS_DELETE_FAIL'
export const COOPENS_DELETE_RESET='COOPENS_DELETE_RESET'

